platform :ios, '15.0'
use_frameworks!

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

post_install do |installer|
  require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
  assertDeploymentTarget(installer)
end
